project:
  type: website
  output-dir: docs

website:
  title: "Python Jumpstart"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - day2.qmd
      - day3.qmd
      
google-analytics: "G-VWGJK762PJ"

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

editor: visual

