---
title: "Study Materials"
---

All you need to do is spend 20 minutes each day watching the video. That's it.

If you want some extra practice, you can also try the exercises provided in the exercise file.

The goal is simple: get familiar with Python, build some confidence, and take the first step towards learning a useful skill.

# Day 1.1: Installing Python

In this video, you’ll see how to download and install Python on a Windows computer, set up the environment correctly, and launch Jupyter Notebook without any confusion. This guide is perfect if you're completely new to programming, data science, or Python development.

We’ll cover:

i.  Downloading and installing Python on Windows

ii. Setting up PATH and verifying installation

iii. Installing Jupyter Notebook using pip

iv. Opening Jupyter Notebook for the first time

v.  Creating and running your first notebook

By the end of this tutorial, you’ll have a fully working Python setup and be ready to start coding in Jupyter Notebook.

{{< video https://youtu.be/wSvnfsplwYw?si=u8oToMJFlXhCd_-Y width="800" height="450" title="Python Jumpstart – Day 1.1" >}}

# Day 1.2: Getting Started with Jupyter Notebook

{{< video https://youtu.be/6EZvhwHHuCQ?si=xutSYICn6EgJHn-Y width="800" height="450" title="Python Jumpstart – Day 1.2" >}}

# Day 2: Data Visualisation with `plotnine`

Go to the script [here](https://thiyangt.github.io/pythonhello/day2.html)


{{< video https://youtu.be/FFoF2mjQHV8?si=PRFoOYYEXOCUn5Xm width="800" height="450" title="Python Jumpstart – Day 1.2" >}}
